### ISSUE TITLE
Consider Timeout Settings

### ISSUE THREAD

**Issue by bradley-holt** [IBM-Cloud/cf-deployment-tracker-client-node#5]
There are two ways to integrate the tracking client. One way is as an npm install script. For example:
https://github.com/cloudant-labs/location-tracker-nodejs/blob/master/package.json#L8

In this scenario, if the Deployment Tracker service is unavailable then I believe that the Node.js script will block until the the request times out. This could slow down deployments when/if the Deployment Tracker service is unavailable. Consider setting a low timeout (e.g. 5 seconds) on the HTTP request to the Deployment Tracker service (https://github.com/IBM-Bluemix/cf-deployment-tracker-client-node/blob/master/tracker.js#L40).

**Comment by glynnbird** [comment]
Passing a value of `timeout` (say 30000) into Restler will allow the library to fail gracefully if the tracking service is slow or unavailable. You can also listen for a `timeout` event emitted by the library, but I would recommend failing silently - the user of our apps would not necessarily concerned if the tracking service had timed out!.
